language: java
jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk7

install: ./gradlew build

# Only upload artifacts from upstream, build on Oracle JDK 7
script: '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${JAVA_HOME}" = "/usr/lib/jvm/java-7-oracle" ] && ./gradlew artifactoryPublish || true'
