package by.dev.madhead.gbp.util;

public interface Constants {
	String ANSI_RESET_CODE = "\u001B[0m";
	String ANSI_HIHGLIGHT_CODE = "\u001B[33m";

	String DEFAULT_GDRIVE_CLIENT_ID_ENV_VAR = "GRADLE_BACKUP_PLUGIN_GDRIVE_CLIENT_ID";
	String DEFAULT_GDRIVE_CLIENT_SECRET_ENV_VAR = "GRADLE_BACKUP_PLUGIN_GDRIVE_CLIENT_SECRET";
	String DEFAULT_GDRIVE_ACCESS_TOKEN_VAR = "GRADLE_BACKUP_PLUGIN_GDRIVE_ACCESS_TOKEN";
	String DEFAULT_GDRIVE_REFRESH_TOKEN_VAR = "GRADLE_BACKUP_PLUGIN_GDRIVE_REFRESH_TOKEN";
}
